### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [IrakliMa/JobScraper#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by IrakliXYZ** [comment]
Thank you for that suggestion. I don't know where and how to find the text for that file. Is there a resource or a generator I can use for this?

**Comment by IrakliXYZ** [comment]
Found a nice resource: https://choosealicense.com/licenses/mit/
Thank you again.
